apiVersion: v1
kind: Namespace
metadata:
  name: iynet
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xyztechnologies-deployment
  namespace: iynet
  labels:
    app: xyztechnologies
spec:
  replicas: 3
  selector:
    matchLabels:
      app: xyztechnologies
  template:
    metadata:
      labels:
        app: xyztechnologies
    spec:
      nodeSelector:
        kubernetes.io/hostname: node5
      containers:
      - name: xyztechnologies
        image: gurubamal/iyztechnologies:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: xyztechnologies-service
  namespace: iynet
spec:
  selector:
    app: xyztechnologies
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort
